### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by AtomicGaming666** [davidteather/TikTokBot#12]
'ffmpeg' is not recognized as an internal or external command,
operable program or batch file.

**Comment by AtomicGaming666** [comment]
ya no your no help bot

**Comment by davidteather** [comment]
Read the readme.md file

**Comment by davidteather** [comment]
It tells you “you must have ffmpeg in your system path” and it gives you an article how to do that

**Comment by AtomicGaming666** [comment]
I have it installed and in my system path

**Comment by AtomicGaming666** [comment]
I followed the steps and stuff

**Comment by davidteather** [comment]
Close your cmd and restart it so it can reload the path variable.
If that doesn't work google the issue further, because it would be a ffmpeg issue

**Comment by AtomicGaming666** [comment]
Kk thx
