### ISSUE TITLE
secs = float(secsval) throw error : "ValueError: could not convert string to float:"

### ISSUE THREAD

**Issue by BenSiso** [davidteather/TikTokBot#13]
Thank for creating this script :)
while trying to run .py file i get this error "ValueError: could not convert string to float:" - after choosing 2-3 and trending.
i am using macOS

**Comment by davidteather** [comment]
What code are you trying to run please provide the .py file’s content you are trying to run

**Comment by BenSiso** [comment]
Hi thanks for the fast respond !  
using **brew reinstall ffmpeg**  
solve it . 
Thanks again!

**Comment by JustDhan** [comment]
Same here but in windows can't execute brew
