### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by artem1480** [davidteather/TikTokBot#15]
Pick a video length (1-3)
1. 2-3 minutes
2. 5-7 minutes
3. 10-12 minutes
1
Select a video type
1. Trending
2. Hashtag
3. User
4. Sound
1
Traceback (most recent call last):
  File "tiktokbot.py", line 114, in <module>
    verifyFp = "verify_" + ''.join(random.choice(string.letters) for num in range(40))
  File "tiktokbot.py", line 114, in <genexpr>
    verifyFp = "verify_" + ''.join(random.choice(string.letters) for num in range(40))
AttributeError: module 'string' has no attribute 'letters'

**Comment by TheClio69** [comment]
Look at this issue : #16.

**Comment by TheClio69** [comment]
@artem1480 please close your issue if your problem is resolved.
