### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by turpez** [davidteather/TikTokBot#16]
Pick a video length (1-3)

2-3 minutes
5-7 minutes
10-12 minutes
1
Select a video type
Trending
Hashtag
User
Sound
1
Traceback (most recent call last):
File "tiktokbot.py", line 114, in
verifyFp = "verify_" + ''.join(random.choice(string.letters) for num in range(40))
File "tiktokbot.py", line 114, in
verifyFp = "verify_" + ''.join(random.choice(string.letters) for num in range(40))
AttributeError: module 'string' has no attribute 'letters'

**Comment by TheClio69** [comment]
Hello @turpez,

You must replace : 
`# The count of the videos to retrieve per specified thing.
# If you're doing a lot of tags or users you might want to decrease count for a quicker runtime
count = 100
verifyFp = "verify_" + ''.join(random.choice(string.letters) for num in range(40))`
with this : 
`# The count of the videos to retrieve per specified thing.
# If you're doing a lot of tags or users you might want to decrease count for a quicker runtime
count = 100
verifyFp = "verify_" + ''.join(random.choice(string.ascii_letters) for num in range(40))`.

If you don't see what has changed, it's the "string.letters" that we replaced with "string.ascii_letters".
Hoping to have solved your problem.

**Comment by TheClio69** [comment]
@turpez please close your issue if your problem is resolved.

**Comment by davidteather** [comment]
Should be fixed by #18
