### ISSUE TITLE
[BUG] - Is the project working on ubuntu?

### ISSUE THREAD

**Issue by MarcoLavoro** [davidteather/TikTokBot#17]
**Describe the bug**

the program stops and give me an error about string has no attribute letters 

**The buggy code**
just the code from

**Expected behavior**

works properly

**Error Trace (if any)**

Traceback (most recent call last):
  File "/home/ma/Scrivania/tiktok/tiktokbot.py", line 114, in <module>
    verifyFp = 'verify_Mycode'.join(random.choice(string.letters) for num in range(40))
  File "/home/ma/Scrivania/tiktok/tiktokbot.py", line 114, in <genexpr>
    verifyFp = 'verify_Mycode'.join(random.choice(string.letters) for num in range(40))
AttributeError: module 'string' has no attribute 'letters'
ma@ma-VirtualBox:~$

**Comment by TheClio69** [comment]
#16

**Comment by TheClio69** [comment]
@MarcoLavoro please close your issue if your problem is resolved.

**Comment by MarcoLavoro** [comment]
Unfortunately i not tried it yet, i will try asap and close the issue if the problem is solved, i have only to change a line in the code, right?

**Comment by TheClio69** [comment]
That's it!

**Comment by TheClio69** [comment]
Let me know if you have any problems or questions.

**Comment by davidteather** [comment]
Should be fixed #18
