### ISSUE TITLE
Getting "Session Expired?" Again And Again.

### ISSUE THREAD

**Issue by samukherjee** [davidteather/TikTokBot#2]

**Comment by davidteather** [comment]
Haven't had the time to move the new TikTok-Api over to this repo yet. 

Here's the TikTok-Api Link if you want to install it and utilize it.
[TikTok-Api](https://github.com/davidteather/TikTok-Api)

**Comment by samukherjee** [comment]
Thanks

**Comment by samukherjee** [comment]
Hey Davidteather, Do u know how do u get that json response in your first line of code...

**Comment by davidteather** [comment]
Closing because Session expired issue was fixed and TikTok-Api was linked
