### ISSUE TITLE
not work !

### ISSUE THREAD

**Issue by todokku** [davidteather/TikTokBot#8]
hi , 
im test it but not work because selenium toktok api can't load video correctly ,
please review & if its possible change api to another build
finest regards

**Comment by davidteather** [comment]
Does it output anything in the console? The tiktoks are not supposed to show up in the browser

**Comment by todokku** [comment]
I don't be try to open video , but not work to start download , please if its possible share your work fine tiktok.py file , windows default path is : 
C:\Users\Administrator\AppData\Local\Programs\Python\Python37\Lib\site-packages\TikTokApi\tiktok.py
waiting for your response
finest regards

**Comment by davidteather** [comment]
When you run the program what does it say in the console? Does anything appear in the downloads folder?

**Comment by todokku** [comment]
1 time downloaded at downloads folder & concat 30 clips into one , after that not work properly

**Comment by davidteather** [comment]
All that it’s supposed to do is combine those tiktok videos are you sure it’s working incorrectly?

**Comment by todokku** [comment]
yeah I'm 100% sure , please share tiktok.py api file for check your own version

**Comment by davidteather** [comment]
The api tiktok.py api is passing all the tests are you sure there’s no ffmpeg errors in the console? There should be at least some error.

**Comment by todokku** [comment]
No, there is no error because it cannot receive even one clip , after get exact clip total value set in main , can compact .

**Comment by davidteather** [comment]
New version has been released. It requires an updated TikTokApi. 

Just run
```
pip install TikTokApi --upgrade
```

Download the code again and run the tiktokbot.py python file.
